wireshark_gui/config/routes.rb
Rails.application.routes.draw do
  get 'interfaces/ethernet'
  get 'interfaces/wireless'
  get 'interfaces/localhost'
  
  get  'interfaces/index'
  post 'interfaces/index'

  root 'home#index'
end

wireshark_gui/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wireshark_gui/app/models/interface.rb
class Interface < ApplicationRecord
end

wireshark_gui/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wireshark_gui/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

wireshark_gui/app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @interfaces = Interface.all
    @colors = ['black', 'red', 'blue', 'yellow']
  end

  def ethernet
    redirect_to interfaces_index_path    
  end

  def wireless
    redirect_to interfaces_index_path
  end

  def localhost
    redirect_to interfaces_index_path
  end
end

wireshark_gui/app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object, dismissal=true)
    capture_haml do
      if object.errors.any?
        haml_tag :div, class: 'row' do
          haml_tag :div, class: 'col-sm-12' do
            haml_tag :div, class: 'errors' do
              haml_tag :div, class: 'alert alert-danger' do
                object_name = t("models.#{object.class.name.underscore.downcase}", default: object.class.name.titleize)
                if dismissal
                  haml_tag :a, '&times;'.html_safe, class: 'close', "data-dismiss" => "alert", "aria-label" => "close"
                end
                haml_tag :p, "#{pluralize(object.errors.count, 'error')} prohibited this #{object_name} from being saved"
                haml_tag :ul do
                  object.errors.full_messages.each do |error|
                    haml_tag :li, error
                  end
                end
              end
            end
          end
        end
      end
    end
  end

  def display_flash
    capture_haml do
      flash.each do |type, message|
        message_class = case type
        when 'notice'
          'success'
        when 'alert'
          'warning'
        when 'error'
          'danger'
        else
          'info'
        end
        haml_tag :div, class: "alert alert-#{message_class} alert-dismissable" do
          haml_tag :a, '&times;'.html_safe, class: 'close', "data-dismiss" => "alert", "aria-label" => "close"
          haml_concat message
        end
      end
    end
  end
end

wireshark_gui/app/helpers/home_helper.rb
module HomeHelper
end

wireshark_gui/app/helpers/interfaces_helper.rb
module InterfacesHelper
end

wireshark_gui/app/views/home/index.html.haml
.row.drop_img
  .col-lg-1
  .col-lg-10
    %a{"data-target" => "#wiresharkModel", "data-toggle" => "modal", :type => "button"}
      = image_tag "wireshark.png", alt: "Wireshark Icon"
  .col-lg-1
  

#wiresharkModel.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "wiresharkModalCenterTitle", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered{:role => "document"}
    .modal-content
      .modal-header
        %h5#wiresharkModalCenterTitle.modal-title Choose An Interface
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = link_to 'eth0', interfaces_ethernet_path, remote: true, class: 'btn btn-warning btn-lg'
        = link_to 'wlan0', interfaces_wireless_path, class: 'btn btn-info btn-lg'
        = link_to 'localhost', interfaces_localhost_path, class: 'btn btn-success btn-lg'

wireshark_gui/app/views/interfaces/index.html.haml
- @interfaces.each_with_index do |interface, i|
  %div
    .bubble{class: "#{@colors[i % 4]}"}= interface.capture
    .pointer{class: "#{@colors[i % 4]}"}
  %div
    .bubble.blurred
    .pointer.blurred

wireshark_gui/app/views/layouts/_navigations.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %div.navbar-header
    = link_to 'Wireshark', root_path, class: 'navbar-brand glow'
  %div.sidenav
    = link_to 'File', root_path, class: 'glow'
    = link_to 'Edit', root_path, class: 'glow'
    = link_to 'Go', root_path, class: 'glow'
    = link_to 'Analyze', root_path, class: 'glow'
    = link_to 'Statistics', root_path, class: 'glow'
    = link_to 'Tools', root_path, class: 'glow'
    = link_to 'Help', root_path, class: 'glow'

wireshark_gui/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wireshark Web App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navigations'
    .container
      = display_flash
      = yield